### PR TITLE
v1.0.6 Boards Manager install support

### PR DESCRIPTION
**Pull request by per1234**
Temporary Boards Manager URL for testing:
https://raw.githubusercontent.com/per1234/MegaCore/bmtest/package_MCUdude_MegaCore_index.json

### CODE REVIEW

**Comment by MCUdude** [comment]
Great, thanks Pert!

**Comment by MCUdude** [comment]
Turns out I just found a typo that prevents the code from building. [This commit](https://github.com/MCUdude/MegaCore/commit/e0e9856196a2b34995837e1da5d01879b43758a5) fixes the issue. This means v1.0.6 doesn't work. Is it best to roll back and release v1.0.6 again?

**Comment by per1234** [comment]
I can do that or just add a 1.0.7 release, it's up to you.

**Comment by MCUdude** [comment]
I decided to edit v1.0.6. It's now ready for the boards manager! Sorry for the hassle 😞

**Pull request merged**
