### PR TITLE
Update CI configuration

### PR DESCRIPTION
**Pull request by per1234**
- Update arduino-ci-script to 1.2.0
- Update tests to use bootloader option
- Add check for files that start with blank line
- Add check for true tabs
- Add check for trailing whitespace
- Add check for non-Unix EOL
- Add check for excess blank lines at end of file
- Add check for files that don't end in newline
- Add check for typos
- Use Travis Buddy to provide notifications of failed CI builds for PRs
- Check for common issues with the bundled libraries and their examples
- Check for common issues with keywords.txt files in bundled libraries

Passing build: https://travis-ci.org/per1234/MegaCore/builds/496992376

TIP: Many of these commits consist primarily of changes to whitespace. When reviewing them, to see what non-whitespace changes were made, you can filter out the whitespace changes by adding `?w=1` to the end of the URL. Example:
https://github.com/MCUdude/MegaCore/commit/c876a43e38781ba1d99f5d41c850f9327ab83ce9?w=1

Fixes https://github.com/MCUdude/MegaCore/issues/91
The only thing on the list I haven't accomplished here is "Check for common problems with library.properties files". I discovered an issue with that function of arduino-ci-script that caused spurious build failures for MegaCore, so I'll need to add that the next time I update the script version used by MegaCore.

### CODE REVIEW

**Comment by MCUdude** [comment]
I honestly don't know why I haven't seen this PR before now. I checked my email and I've even gotten a notification! I'm not trying to be slow on purpose, I swear. It's no excuse though...

I'm planning to do a new MegaCore release soon. It's been over a year since the last release, and a lot has happened since then. It would be great if you would resolve the issues listed above. Then I could (finally) merge this PR.

**Comment by MCUdude** [comment]
@per1234 I'm sorry to bother you, but it would be great if you'd look into this. I think all that's needed is a rebase.

**Comment by per1234** [comment]
I'm sorry about being so slow on this and the Boards Manager releases. I've just been swamped with work the last few days. I'll get to it today for sure.

The good news is I learned something about Travis CI that should allow me to significantly reduce the build time by doing the formatting and typo checks in a single dedicated job, rather than doing them redundantly in every single job. I'll go ahead and implement that in this PR.

**Comment by MCUdude** [comment]
> I'm sorry about being so slow on this and the Boards Manager releases. I've just been swamped with work the last few days. I'll get to it today for sure.

There's no hurry, take your time 🙂 You're usually so quick to respond, so for a second, I was a little afraid I've scared you away since I haven't been the best to pay attention to all Github notifications.

**Comment by per1234** [comment]
OK, I have rebased to fix the merge conflicts and also updated the Travis CI configuration so that there are dedicated jobs for:
- Formatting Checks
- Spell Check
- arduino-ci-script Extra Checks ([`check_library_structure`](https://github.com/per1234/arduino-ci-script#check_library_structure-basepath-depth) and [`check_keywords_txt`](https://github.com/per1234/arduino-ci-script#check_keywords_txt-searchpath-maximumsearchdepth))

The dedicated jobs for those checks should make the build a bit faster, since they will not be done redundantly in every single compilation test job. Previously, I had the configuration so that the job would fail immediately if there was an issue with formatting/typos/etc., without even starting on the compilation tests part of the job. Now, the dedicated jobs for those checks happen first, so you can still quickly see if they failed by looking at the build, but they will not block the compilation test jobs from proceeding.

**Pull request merged**
