### PR TITLE
Add missing parentheses to analogInputToDigitalPin macro argument

### PR DESCRIPTION
**Pull request by per1234**

### CODE REVIEW

**Comment by MCUdude** [comment]
Huh, that one must have passed. Thanks!
Did someone report this in the forums, or did you find it yourself?

**Comment by per1234** [comment]
I found it. I recently added ATmega1281/2561 support to the MegaCore:standard variant as well as modifying it for Wiring 1.0/1.1 pinout for a different hardware package so I've gotten pretty familiar with the file. I remember you saying you were thinking of adding those parts to MegaCore. I need to have another look over it but if it's something that might be useful to you you're welcome to it and I'd be happy to do the boards.txt and Makefile modifications also. I'm not sure I have the skills to do the core and library work and I don't have those parts to do testing but at least it's a start.

**Comment by MCUdude** [comment]
I'm interested in ATmega1281/2561 support in this core, but I think I should get my hands on some before pushing code out on the master branch. I also think I'll stick with the same pinout as I already use for the ATmega64/128

**Comment by per1234** [comment]
> I think I should get my hands on some before pushing code out on the master branch

Sounds like a good idea. Let me know if you ever want me to make a pull request for it.

>  I also think I'll stick with the same pinout

Yes, I understand and agree that's for the best. To be clear, I made 2 versions of the file, one with the current MegaCore pinout but added support for the new parts, and another that has the Wiring pinouts. I was offering the former. This was for an SD card [bootloader](https://github.com/zevero/avr_boot) but I'm thinking of making a separate package just for Wiring boards. I don't want to make a whole core for it, just my hardware definitions and their bootloaders, so it would be nice if I could reference MegaCore to give better compatibility for those parts. MightyCore and MegaCore will already support their other 4 boards. I saw Visual Micro recently made a Wiring plugin for Atmel Studio so there must be some interest in the project still.

**Pull request merged**
