### PR TITLE
v1.0.0 Boards Manager install support

### PR DESCRIPTION
**Pull request by per1234**
Boards Manager URL for testing: https://raw.githubusercontent.com/per1234/MegaCore/bmtest/package_MCUdude_MegaCore_index.json

Boards Manager entry:
clipboard01

Boards Manager URL after this PR merged: https://mcudude.github.io/MegaCore/package_MCUdude_MegaCore_index.json

### CODE REVIEW

**Comment by MCUdude** [comment]
Thank you so much! After some more testing it would be nice to add to to the "Arduino on other Atmel chips" page.

**Comment by per1234** [comment]
You're welcome. Also should be added to https://github.com/arduino/Arduino/wiki/Unofficial-list-of-3rd-party-boards-support-urls I'm happy to do that if you want, just let me know when you think it's ready.

**Comment by MCUdude** [comment]
I haven't received my ATmega128 test board in the mail yet, so I still haven't been able to squeeze out any bugs by testing yet. I'm sure the code will run, but Murphy's law always gets me ;) In the meantime I'm thinking about improving the documentation of this core. Topics like "How to port a library" may come in handy for some. Any topics you think should be added?

**Comment by per1234** [comment]
One thing to consider adding to the documentation is a note that if any of the libraries included with MegaCore are updated using Library Manager then the version installed with Library Manager will override the MegaCore version of the library. See https://github.com/arduino/Arduino/issues/4064 for more information. I haven't been able to find any workaround for this issue other than to document the issue and tell the user they should move the updated library from their {sketchbook}/libraries folder to {IDE install folder}/libraries(for example: https://github.com/JChristensen/mighty-1284p/commit/ceed9b68cc913d8465ef10ccb59d6bbc14b870b6). It's a difficult concept to explain without adding a lot of text to the documentation. There is currently some work being done towards a fix(https://github.com/arduino/arduino-builder/pull/123) but so far it only addresses the issue with cores that use other architectures so doesn't help for MegaCore and MightyCore(https://github.com/arduino/arduino-builder/pull/123#issuecomment-192626768). Even if the issue is fixed there will still be lots of users on the previous versions of the IDE that still have the issue.

**Comment by MCUdude** [comment]
I got the ATmega128 breakout board in the mail today, and it works like a charm! :smile: I think it's ready to be published on the "Arduino on other Atmel chips" and "Unofficial list of 3rd party boards" page. Now I  need people to test it and let me know if there are any bugs

**Comment by per1234** [comment]
I've added MegaCore to both pages.

**Pull request merged**
