### PR TITLE
Update arduino-ci-script subtree to 1.0.0 tag

### PR DESCRIPTION
**Pull request by per1234**
https://github.com/per1234/arduino-ci-script/tree/1.0.0

- Add testing for Arduino IDE 1.8.3
- Improve efficiency of the build process
- Reduce unnecessary log verbosity
- Detect more hardware definition issues
- Detect library issues that don't affect compilation
- Various improvements of reliability and error handling

### CODE REVIEW

**Comment by per1234** [comment]
The whole build of this PR has been successful except for some reason this pesky job 49 was canceled. @MCUdude maybe if you click the "Restart Job" button here:
https://travis-ci.org/MCUdude/MegaCore/jobs/244917733
to see if the build can be completed without requiring a full redo?

**Comment by per1234** [comment]
OK, job 49 ended up completing successfully!

**Comment by MCUdude** [comment]
Thank you for this!
I'm sorry for not being more available, I've been busy moving to a new house.
How is the MegaCore dev board working for you?

**Comment by per1234** [comment]
No worries. I hope the move is going well for you. I haven't had time to do anything fancy with the MegaCore board yet but I played around with it with a few sketches and it works great. Thanks! The capacitors and ATtiny2313 for the ATtiny board arrived today. I think I'm just waiting for the last of the regulators before I have everything I need to assemble it.

**Pull request merged**
