### PR TITLE
Update wiring.c

### PR DESCRIPTION
**Pull request by zharovdv**
2MHz delayMicroseconds block based on 1MHz block

### CODE REVIEW

**Comment by MCUdude** [comment]
Why do we need a 2 MHz option? there's no internal 2 MHz clock option for any ATmega, and 2 MHz is not even an option in the boards menu,

**Comment by zharovdv** [comment]
I use this atmega128 with 2MHz internal clock option with MegaCore - so it tested and work.

**Comment by zharovdv** [comment]
I have a boards menu patch with atmega128 2MHz too

**Comment by MCUdude** [comment]
I'm sorry, but I don't think I'll merge this PR. 2 MHz is rarely used, and it does not bring any "benefits" when it comes to operating voltage and baud rate errors when compared to 8 MHz.

But, that's why we have forks!

**Comment by zharovdv** [comment]
No problem.

Sometimes we need in balance between performance and power consumption. In this situation 2MHz may be good choise (it so in my case). Baud rate not problem at all using with OSCCAL and auto calibration like here "AVR055: Using a 32 kHz crystal to calibrate the internal RC oscillator" it works perfect.

**Pull request closed without merging**
