### PR TITLE
Merge avr-100-pin branch into master

### PR DESCRIPTION
**Pull request by MCUdude**
I've been working on this branch for a while now. Support for ATmega640/1280/2560 is added, and Optiboot has gotten a major cleanup and is now maintained from [its own repository](https://github.com/MCUdude/optiboot_flash). The Arduino core files now supports all my Arduino cores, and is also maintained from [its own repository](https://github.com/MCUdude/MCUdude_corefiles). Travis CI is now implemented, which makes testing and bug smacking much easier.

### CODE REVIEW

**Comment by MCUdude** [comment]
I need some help here. I tried to resolve this issue from the command line, but git added `<<<<<<< HEAD:` to a lot of the files, which obviously caused Travis build to fail. I've now rolled it back, but how can I merge this PR without messing everything up again? Will the commit history from the avr-100-pin branch be added to the master?

**Comment by per1234** [comment]
There are some conflicts as the history of the branches are combined because they have diverged a little. I just had a try at resolving them but I was tripped up somehow by the subtree commits so I need to redo it. All the commit history from the avr-100-pin branch should be added to master during the merge. I feel like these should be rebased onto it so that none of the history of the master branch is changed. The one I saw that became redundant was https://github.com/MCUdude/MegaCore/commit/c6ae0fd7d42dc79830583af2e1df75485f1d9515 because, other than breaking line 70 into two lines, that change had already been made on the master branch at https://github.com/MCUdude/MegaCore/commit/30723e02403ffb0d97b6d1183a503f83501ea97c so I squashed that change into https://github.com/MCUdude/MegaCore/commit/e546d433037a60b61179a52f32cb62ada96958bd.

I'm a little too tired now to make sure I don't mess this up but I'll have another try in the morning if you haven't fixed it by then. Resolving merge conflicts always make my head hurt. I always keep my finger crossed when I'm doing a rebase in hopes that I won't have any to deal with.

**Comment by per1234** [comment]
Just wanted to give an update on my progress (or lack thereof). It turns out that for some crazy reason Git puts subtrees into the repository root when you rebase. I couldn't figure out why that kept happening to me. The only workaround I've found is that all the subtree merges need to be omitted from the rebase and then added back in one at a time:
http://stackoverflow.com/questions/12858199
So I'll give it a try and then submit a PR to master if I can get it to work right.

**Comment by per1234** [comment]
Well, this is what I've managed:
https://github.com/per1234/MegaCore/pull/1
That's a preview of what the pull request would look like if I submitted it.

The main thing I don't like is that the author field for every one of your commits says "MCUdude committed with per1234" now. I don't know how to get rid of that.

I didn't end up exactly reproducing your subtree commits for optiboot_flash and MCUdude_corefiles. We must have a different system for doing that because mine happen in only a single commit but yours happen in multiple commits. I follow these instructions:
https://git-scm.com/book/en/v1/Git-Tools-Subtree-Merging
Interestingly, my arduino-ci-script subtree commits didn't have the issue with Git moving them to the root of the repository.

**Comment by MCUdude** [comment]
> Well, this is what I've managed:
per1234#1
That's a preview of what the pull request would look like if I submitted it.

I have no problems with you getting you name all over this merge. After all, you're been incredibly helpful.

Does this mean you would have to create a new pull request, where you've merged avr-100-pin into the master of your fork, and then I merge your fork into this repos master, right?

**Comment by per1234** [comment]
>Does this mean you would have to create a new pull request, where you've merged avr-100-pin into the master of your fork, and then I merge your fork into this repos master, right?

That's correct. I would just need to submit a pull request to merge my branch:
https://github.com/per1234/MegaCore/tree/rebase-avr-100-pin
into your master branch. In that branch I've already rebased all commits from your `avr-100-pin` branch onto your `master` branch so it will be able to be merged to your master branch without any conflicts. 

I just need to wait for the Travis CI build of my branch and then I can submit the pull request. Unfortunately I just noticed that the build was blocked from starting by an ongoing build of a previous attempt that I had replaced but forgot to cancel so it's just getting started now:
https://travis-ci.org/per1234/MegaCore/builds/234693547

**Comment by MCUdude** [comment]
I got som help from a colleague, which is much more experienced with git than I am. We were able to merge the two branches, and created a new one, `v2.0.0` which Travis is now working on. Let's see how it goes 🤞

**Comment by per1234** [comment]
My work is more clean but go with whatever you're happy with.

**Comment by MCUdude** [comment]
I'd allways prefer the cleanest. How is yours cleaner then `v2.0.0`?

**Comment by per1234** [comment]
I redid the subtree commits after the rebase so that they correctly place the subtrees in the correct subfolder of the repository, as the original commits did. Your subtree commits put the subtrees in the root folder, which required you to later add the commits moving them to the correct folder:
https://github.com/MCUdude/MegaCore/commit/ba386ff2ff9b1b19cfc3d5a9e4a4c391265cdc61
https://github.com/MCUdude/MegaCore/commit/ee77ab8478e5ba25b95a42b1afd021a3137f058e
This means that MegaCore is broken at all points in history between the subtree commits and the commits listed above. I always try to create a commit history where the code is in a working state at any point in history. This allows you to step back through history when you are troubleshooting a bug to determine exactly which commit introduced the bug. There's a good chance that nobody will ever need to do that in this case but it's just a general best practice.

The subtrees initially being added to the root in your `v2.0.0` branch also caused the strange conflict in README.md which required you to add https://github.com/MCUdude/MegaCore/commit/e2bb8b7c7130d64cc975cd73343cfb8b8892779b. This also resulted in the README.md file being missing from avr/cores/MCUdude_corefiles/, which was not the case in the `avr-100-pin` branch. Not really a big deal but fairly easy to avoid.

The final result is essentially the same in either branch so either way you go it will be fine. I get kind of uptight about commit histories because I end up digging through them quite often. Mostly this is because I don't really know what I'm doing and I have to try to "reverse engineer" the purpose of some code that would probably be obvious to someone with more knowledge. When find the commit where that line was added or modified and it's a some non-atomic changes with a commit message that only says "Update foo.c" it makes me want to tear my hair out!

**Comment by MCUdude** [comment]
Yep, my colleagues fix messes up the subtrees. If you create a PR, i'll merge it into the master

**Pull request closed without merging**
